import Header from "@/components/Header";
import "./css/globals.css";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Luxelane",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="font-bodyFont text-darkText">
        <Header />

        {children}
      </body>
    </html>
  );
}
